
# joe playbooks/remote_builds.yml
# ansible-playbook -i variables/hosts.yaml -e 'ansible_ssh_user=ansible' --private-key ~/.ssh/orchestration-iaas-no.pem playbooks/remote_builds.yml

---
- hosts: "{{active_hosts_groups}}"
  vars_files:
    - ../variables/remote_builds-list.json
  remote_user: orchestrator
  # https://stackoverflow.com/questions/27444204/run-ansible-playbook-with-sudo
  become: yes
  become_method: sudo
  gather_facts: false

  tasks:
  
  - import_tasks: "include/_debug_active_hosts.yml"
    tags: [debug]

  - import_tasks: "include/_load_host_speciffic_data.yml"
    tags: [always]

  # -----------------------------------
  # Real build tasks
  # -----------------------------------
  - name: Run remote build task (on remote machine)
    with_items: "{{ items_array }}"
    when: "{{ (item.hosts is not defined or ((active_hosts_groups | intersect(item.hosts)) | length>0) ) and (active_tags is not defined or ((active_tags | intersect(item._tags)) | length>0) ) }}" # check `hosts` and `_tags` matching
    # https://docs.ansible.com/ansible/latest/modules/command_module.html
    command: "{{ item.command }}"
    args:
      chdir: "{{item.path | default(None) }}" # default is None
    become_user: "{{ item.user | default(omit) }}"
    # https://stackoverflow.com/questions/44004727/how-to-run-local-command-via-ansible-playbook?rq=1
