# joe playbooks/yarns.yml
# ansible-playbook -i variables/hosts.yaml -e 'ansible_ssh_user=ansible' --private-key ~/.ssh/orchestration-iaas-no.pem playbooks/yarns.yml

---
- hosts: "{{active_hosts_groups}}"
  vars_files:
    - ../variables/yarns-list.json
  remote_user: orchestrator
  # https://stackoverflow.com/questions/27444204/run-ansible-playbook-with-sudo
  become: yes
  become_method: sudo
  gather_facts: false

  tasks:

  - import_tasks: "include/_debug_active_hosts.yml"
    tags: [debug]

  - import_tasks: "include/_load_host_speciffic_data.yml"
    tags: [always]

# -----------------------------------
# Real yarns tasks
# -----------------------------------
#  - name: Run Yarn typescript
#    with_items: "{{ items_array }}"
#    when: "{{ item.hosts is not defined or ((active_hosts_groups | intersect(item.hosts)) | length>0) }}" # check hosts matching
#    https://docs.ansible.com/ansible/2.6/modules/yarn_module.html
#    yarn:
#      name: typescript
#      global: yes
#      state: 'present'

#  - name: Run Yarn tools
    # with_items: "{{ items_array }}"
    # when: "{{ item.hosts is not defined or ((active_hosts_groups | intersect(item.hosts)) | length>0) }}" # check hosts matching
    # https://docs.ansible.com/ansible/2.6/modules/yarn_module.html
    # yarn:
      # name: "{{item.name}}"
      # path: "{{item.path | default(None) }}" # default is None
      # global: "{{item.global | default(false) }}" # default is false
      # production: "{{item.production | default(false) }}" # default is false
      # state: "{{item.state | default('present') }}" # default is 'present'

  - name: Run Yarn tools
    with_items: "{{ items_array }}"
    when: "{{ item.hosts is not defined or ((active_hosts_groups | intersect(item.hosts)) | length>0) }}" # check hosts matching
    # https://docs.ansible.com/ansible/latest/modules/command_module.html
    # equivalent for buggy yarn module (previous task)
    # https://gist.github.com/jonlabelle/c082700c1c249d986faecbd5abf7d65b
    # https://yarnpkg.com/lang/en/docs/cli/global/
    command: yarn {{'global' if item.global else '' }} {{'add ' + item.name if item.name else ''}} {{'--production' if item.production else ''}}
    args:
      chdir: "{{item.path | default(None) }}" # default is None
      # state: "{{item.state | default('present') }}" # default is 'present'
