# Usually placed in `/etc/ansible/hosts` 
# or invited with explicit `-i` CLI parameter

orchestrators:
  hosts:
    orchestrator-1:
        ansible_host: 158.39.75.31
        ansible_port: 22

instances:
  hosts:
    instance-1:
        ansible_host: 158.39.75.120
        ansible_python_interpreter: /usr/bin/python3

blogs:
  hosts:
    blog-1:
        ansible_host: 158.37.63.168
        ansible_python_interpreter: /usr/bin/python3

services:
  hosts:
    service-1:
        ansible_host: 158.39.75.130
        ansible_python_interpreter: /usr/bin/python3

litterra:
  hosts:
    litterra-1:
      ansible_host: 158.39.48.39
      ansible_python_interpreter: /usr/bin/python3