# Usually placed in `/etc/ansible/hosts` 
# or invited with explicit `-i` CLI parameter

# Used to orchestrate services
orchestrators:
  hosts:
    orchestrator-1:
        ansible_host: 158.39.75.31
        ansible_port: 22

# Used to run colabo.space apps
instances:
  hosts:
    # instance-1:
    #     ansible_host: 158.39.75.120
    #     ansible_python_interpreter: /usr/bin/python3
    colabo.space-apps-1:
        ansible_host: 158.39.75.119
        ansible_python_interpreter: /usr/bin/python3

# Used to run blogs (mostly ghost)
blogs:
  hosts:
    blog-1:
        ansible_host: 158.37.63.168
        ansible_python_interpreter: /usr/bin/python3

# Used to run time demanding backend services
services:
  hosts:
    service-1:
        ansible_host: 158.39.75.130
        ansible_python_interpreter: /usr/bin/python3

# Used to run DH (litterra, bukvik, ...) sites, services, etc
litterra:
  hosts:
    litterra-1:
      ansible_host: 158.39.48.39
      ansible_python_interpreter: /usr/bin/python3